#!/usr/bin/env bash
# generate-health-base.sh — 生成 / 更新 wiki/health.base 健康仪表盘
# 用法：bash generate-health-base.sh <wiki-root>
set -eo pipefail

WIKI_ROOT="${1:-.}"
OUT="$WIKI_ROOT/wiki/health.base"

[[ -d "$WIKI_ROOT/wiki" ]] || {
  echo "{\"status\":\"fail\",\"errors\":[{\"file\":\"$WIKI_ROOT\",\"rule\":\"missing-wiki-dir\",\"message\":\"找不到 wiki/\"}]}"
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

count_errors() {
  local script="$1"
  local out
  out=$("$SCRIPT_DIR/$script" "$WIKI_ROOT" 2>/dev/null || true)
  if jq -e '.errors' <<< "$out" >/dev/null 2>&1; then
    jq '.errors | length' <<< "$out"
  else
    echo 0
  fi
}

total_pages=$(find "$WIKI_ROOT/wiki" -type f -name '*.md' ! -name 'health.base' | wc -l | tr -d ' ')
orphans_count=$(count_errors check-orphans.sh)
fm_errors=$(count_errors check-frontmatter.sh)
drift_count=$(count_errors check-index-drift.sh)

# 从 log.md 找最后一条 ingest
last_ingest=""
if [[ -f "$WIKI_ROOT/log.md" ]]; then
  last_ingest=$(grep -E '\| ingest \|' "$WIKI_ROOT/log.md" | tail -n1 | awk -F' \\| ' '{print $1}' || true)
fi
last_ingest="${last_ingest:-never}"

timestamp="${LWK_NOW:-$(date '+%Y-%m-%d %H:%M')}"

cat > "$OUT" <<BASE
# Auto-generated by llm-wiki-kit lint Skill. Do not edit by hand.
# Regenerate: bash skills/lint/scripts/generate-health-base.sh <wiki-root>

filters:
  and:
    - file.ext == "md"

views:
  - type: table
    name: Wiki Health
    order:
      - file.name
      - total_pages
      - orphans_count
      - frontmatter_errors_count
      - index_drift_count
      - last_ingest_at
      - updated_at

properties:
  total_pages: ${total_pages}
  orphans_count: ${orphans_count}
  frontmatter_errors_count: ${fm_errors}
  index_drift_count: ${drift_count}
  last_ingest_at: "${last_ingest}"
  updated_at: "${timestamp}"
BASE

jq -nc --arg f "$OUT" '{status:"pass", errors:[], file:$f}'
